FROM python:3.14.2

WORKDIR /clickstream

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# COPY ../script script

# CMD ["python", "script/clickstream.py"]
CMD ["sleep", "infinity"]