services:
  localstack:
    container_name: localstack_container
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    ports:
      - '4566:4566'
    volumes:  
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - clickstream-network

  clickstream_app:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
      
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
        - ../script:/clickstream/script
        - ../data_generator/data:/clickstream/data
    depends_on:
        - localstack
    networks:
      - clickstream-network

networks:
  clickstream-network:
    external: true